sample_flow = {
    "nodes": [
        {
            "id": "94969",
            "type": "Start",
            "data": {"function": "__ignore__"},
            "position": {"x": 478, "y": 257},
            "positionAbsolute": {"x": 478, "y": 257},
            "width": 82,
            "height": 26,
            "selected": False,
        },
        {
            "id": "95082",
            "type": "GetVariable",
            "data": {
                "kwargs": {"variable_name": "swapi_url"},
                "function": "__ignore__",
            },
            "position": {"x": 475.5, "y": 301.25},
            "positionAbsolute": {"x": 475.5, "y": 301.25},
            "width": 82,
            "height": 26,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "93043",
            "type": "HttpGet",
            "data": {"args": [None], "function": "requests.get"},
            "position": {"x": 612, "y": 259.75},
            "positionAbsolute": {"x": 612, "y": 259.75},
            "width": 210,
            "height": 50,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "6367",
            "type": "JsonExtract",
            "data": {
                "kwargs": {"expression": "$.results"},
                "function": "custom.extract_json",
            },
            "position": {"x": 884.5, "y": 258.25},
            "positionAbsolute": {"x": 884.5, "y": 258.25},
            "width": 162,
            "height": 66,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "77775",
            "type": "ForEach",
            "data": {
                "kwargs": {"next_function": "72374"},
                "function": "custom.for_each",
            },
            "position": {"x": 1097, "y": 257.75},
            "positionAbsolute": {"x": 1097, "y": 257.75},
            "width": 98,
            "height": 58,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "72374",
            "type": "JsonExtract",
            "data": {
                "kwargs": {"expression": "$.name"},
                "function": "custom.extract_json",
            },
            "position": {"x": 1253.5, "y": 257.75},
            "positionAbsolute": {"x": 1253.5, "y": 257.75},
            "width": 162,
            "height": 66,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "59697",
            "type": "Branch",
            "data": {
                "kwargs": {"true": None, "false": None},
                "function": "custom.branch",
            },
            "position": {"x": 1670, "y": 281.25},
            "positionAbsolute": {"x": 1670, "y": 281.25},
            "width": 98,
            "height": 58,
            "selected": False,
            "dragging": False,
        },
        {
            "id": "51034",
            "type": "SetVariable",
            "data": {
                "kwargs": {"variable_name": "name", "value": None},
                "function": "custom.set_variable",
            },
            "position": {"x": 1457, "y": 258.25},
            "positionAbsolute": {"x": 1457, "y": 258.25},
            "width": 162,
            "height": 66,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "88179",
            "type": "Or",
            "data": {"args": [False, False], "function": "operator.or_"},
            "position": {"x": 1552, "y": 348.75},
            "positionAbsolute": {"x": 1552, "y": 348.75},
            "width": 66,
            "height": 34,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "92109",
            "type": "Contains",
            "data": {"args": ["C", None], "function": "operator.contains"},
            "position": {"x": 1330, "y": 400.25},
            "positionAbsolute": {"x": 1330, "y": 400.25},
            "width": 130,
            "height": 42,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "85893",
            "type": "GetVariable",
            "data": {"kwargs": {"variable_name": "name"}, "function": "__ignore__"},
            "position": {"x": 1162.5, "y": 383.25},
            "positionAbsolute": {"x": 1162.5, "y": 383.25},
            "width": 82,
            "height": 26,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "77638",
            "type": "Contains",
            "data": {"args": ["Luke", None], "function": "operator.contains"},
            "position": {"x": 1329, "y": 340.25},
            "positionAbsolute": {"x": 1329, "y": 340.25},
            "width": 130,
            "height": 42,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "25228",
            "type": "Print",
            "data": {"args": [None], "function": "builtins.print"},
            "position": {"x": 1828, "y": 303.25},
            "positionAbsolute": {"x": 1828, "y": 303.25},
            "width": 162,
            "height": 50,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "82889",
            "type": "GetVariable",
            "data": {"kwargs": {"variable_name": "name"}, "function": "__ignore__"},
            "position": {"x": 1701.5, "y": 351.75},
            "positionAbsolute": {"x": 1701.5, "y": 351.75},
            "width": 82,
            "height": 26,
            "dragging": False,
            "selected": False,
        },
    ],
    "edges": [
        {
            "source": "94969",
            "sourceHandle": "start",
            "target": "93043",
            "targetHandle": "e-in",
            "id": "xyflow__edge-94969start-93043e-in",
            "selected": False,
        },
        {
            "source": "95082",
            "sourceHandle": "swapi_url",
            "target": "93043",
            "targetHandle": "0",
            "id": "xyflow__edge-95082swapi_url-930430",
            "selected": False,
        },
        {
            "source": "93043",
            "sourceHandle": "e-out",
            "target": "6367",
            "targetHandle": "e-in",
            "id": "xyflow__edge-93043e-out-6367e-in",
            "selected": False,
        },
        {
            "source": "93043",
            "sourceHandle": "__ignore__",
            "target": "6367",
            "targetHandle": "json_obj",
            "id": "xyflow__edge-93043__ignore__-6367json_obj",
            "selected": False,
        },
        {
            "source": "6367",
            "sourceHandle": "e-out",
            "target": "77775",
            "targetHandle": "e-in",
            "id": "xyflow__edge-6367e-out-77775e-in",
            "selected": False,
        },
        {
            "source": "6367",
            "sourceHandle": "__ignore__",
            "target": "77775",
            "targetHandle": "array",
            "id": "xyflow__edge-6367__ignore__-77775array",
            "selected": False,
        },
        {
            "source": "77775",
            "sourceHandle": "next_function",
            "target": "72374",
            "targetHandle": "e-in",
            "id": "xyflow__edge-77775next_function-72374e-in",
            "selected": False,
        },
        {
            "source": "77775",
            "sourceHandle": "__ignore__",
            "target": "72374",
            "targetHandle": "json_obj",
            "id": "xyflow__edge-77775__ignore__-72374json_obj",
            "selected": False,
        },
        {
            "source": "72374",
            "sourceHandle": "e-out",
            "target": "51034",
            "targetHandle": "e-in",
            "id": "xyflow__edge-72374e-out-51034e-in",
            "selected": False,
        },
        {
            "source": "72374",
            "sourceHandle": "__ignore__",
            "target": "51034",
            "targetHandle": "value",
            "id": "xyflow__edge-72374__ignore__-51034value",
            "selected": False,
        },
        {
            "source": "51034",
            "sourceHandle": "e-out",
            "target": "59697",
            "targetHandle": "e-in",
            "id": "xyflow__edge-51034e-out-59697e-in",
            "selected": False,
        },
        {
            "source": "88179",
            "sourceHandle": "__ignore__",
            "target": "59697",
            "targetHandle": "condition",
            "id": "xyflow__edge-88179__ignore__-59697condition",
            "selected": False,
        },
        {
            "source": "92109",
            "sourceHandle": "__ignore__",
            "target": "88179",
            "targetHandle": "1",
            "id": "xyflow__edge-92109__ignore__-881791",
            "selected": False,
        },
        {
            "source": "77638",
            "sourceHandle": "__ignore__",
            "target": "88179",
            "targetHandle": "0",
            "id": "xyflow__edge-77638__ignore__-881790",
            "selected": False,
        },
        {
            "source": "85893",
            "sourceHandle": "name",
            "target": "77638",
            "targetHandle": "1",
            "id": "xyflow__edge-85893name-776381",
        },
        {
            "source": "85893",
            "sourceHandle": "name",
            "target": "92109",
            "targetHandle": "1",
            "id": "xyflow__edge-85893name-921091",
        },
        {
            "source": "59697",
            "sourceHandle": "true",
            "target": "25228",
            "targetHandle": "e-in",
            "id": "xyflow__edge-59697true-25228e-in",
        },
        {
            "source": "82889",
            "sourceHandle": "name",
            "target": "25228",
            "targetHandle": "0",
            "id": "xyflow__edge-82889name-252280",
        },
    ],
    "variables": {"swapi_url": "https://swapi.dev/api/people/", "name": ""},
}

exec_edges = [
    {
        "id": "xyflow__edge-93043e-out-6367e-in",
        "source": "93043",
        "sourceHandle": "e-out",
        "target": "6367",
        "targetHandle": "e-in",
        "selected": False,
    },
    {
        "id": "xyflow__edge-6367e-out-77775e-in",
        "source": "6367",
        "sourceHandle": "e-out",
        "target": "77775",
        "targetHandle": "e-in",
        "selected": False,
    },
    {
        "id": "xyflow__edge-72374e-out-51034e-in",
        "source": "72374",
        "sourceHandle": "e-out",
        "target": "51034",
        "targetHandle": "e-in",
        "selected": False,
    },
    {
        "id": "xyflow__edge-51034e-out-59697e-in",
        "source": "51034",
        "sourceHandle": "e-out",
        "target": "59697",
        "targetHandle": "e-in",
        "selected": False,
    },
]
except_edges = [
    {
        "id": "xyflow__edge-94969start-93043e-in",
        "source": "94969",
        "sourceHandle": "start",
        "target": "93043",
        "targetHandle": "e-in",
        "selected": False,
    },
    {
        "id": "xyflow__edge-77775next_function-72374e-in",
        "source": "77775",
        "sourceHandle": "next_function",
        "target": "72374",
        "targetHandle": "e-in",
        "selected": False,
    },
    {
        "id": "xyflow__edge-59697true-25228e-in",
        "source": "59697",
        "sourceHandle": "true",
        "target": "25228",
        "targetHandle": "e-in",
    },
]
arg_edges = [
    {
        "id": "xyflow__edge-95082swapi_url-930430",
        "source": "95082",
        "sourceHandle": "swapi_url",
        "target": "93043",
        "targetHandle": "0",
        "selected": False,
    },
    {
        "id": "xyflow__edge-92109__ignore__-881791",
        "source": "92109",
        "sourceHandle": "__ignore__",
        "target": "88179",
        "targetHandle": "1",
        "selected": False,
    },
    {
        "id": "xyflow__edge-77638__ignore__-881790",
        "source": "77638",
        "sourceHandle": "__ignore__",
        "target": "88179",
        "targetHandle": "0",
        "selected": False,
    },
    {
        "id": "xyflow__edge-85893name-776381",
        "source": "85893",
        "sourceHandle": "name",
        "target": "77638",
        "targetHandle": "1",
    },
    {
        "id": "xyflow__edge-85893name-921091",
        "source": "85893",
        "sourceHandle": "name",
        "target": "92109",
        "targetHandle": "1",
    },
    {
        "id": "xyflow__edge-82889name-252280",
        "source": "82889",
        "sourceHandle": "name",
        "target": "25228",
        "targetHandle": "0",
    },
]
kwarg_edges = [
    {
        "id": "xyflow__edge-93043__ignore__-6367json_obj",
        "source": "93043",
        "sourceHandle": "__ignore__",
        "target": "6367",
        "targetHandle": "json_obj",
        "selected": False,
    },
    {
        "id": "xyflow__edge-6367__ignore__-77775array",
        "source": "6367",
        "sourceHandle": "__ignore__",
        "target": "77775",
        "targetHandle": "array",
        "selected": False,
    },
    {
        "id": "xyflow__edge-77775__ignore__-72374json_obj",
        "source": "77775",
        "sourceHandle": "__ignore__",
        "target": "72374",
        "targetHandle": "json_obj",
        "selected": False,
    },
    {
        "id": "xyflow__edge-72374__ignore__-51034value",
        "source": "72374",
        "sourceHandle": "__ignore__",
        "target": "51034",
        "targetHandle": "value",
        "selected": False,
    },
    {
        "id": "xyflow__edge-88179__ignore__-59697condition",
        "source": "88179",
        "sourceHandle": "__ignore__",
        "target": "59697",
        "targetHandle": "condition",
        "selected": False,
    },
]

sample_two_flow = {
    "start_id": "1",
    "nodes": [
        {
            "id": "1",
            "type": "anything",
            "data": {
                "args": [1, 2],
                "function": "operator.add",
            },
            "position": {"x": 475.5, "y": 301.25},
            "positionAbsolute": {"x": 475.5, "y": 301.25},
            "width": 82,
            "height": 26,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "2",
            "type": "anythong",
            "data": {
                "args": [None, 3],
                "function": "operator.mul",
            },
            "position": {"x": 612, "y": 259.75},
            "positionAbsolute": {"x": 612, "y": 259.75},
            "width": 210,
            "height": 50,
            "dragging": False,
            "selected": False,
        },
    ],
    "edges": [
        {
            "id": "e1e-e2e",
            "source": "1",
            "sourceHandle": "e-out",
            "target": "2",
            "targetHandle": "e-in",
        },
        {
            "id": "e1-2",
            "source": "1",
            "sourceHandle": "__ignore__",
            "target": "2",
            "targetHandle": "0",
        },
    ],
    "variables": {},
}

sample_fail_flow = {
    "start_id": "1",
    "nodes": [
        {
            "id": "1",
            "type": "anything",
            "data": {
                "args": [1, 2],
                "function": "invalid_function",
            },
            "position": {"x": 475.5, "y": 301.25},
            "positionAbsolute": {"x": 475.5, "y": 301.25},
            "width": 82,
            "height": 26,
            "dragging": False,
            "selected": False,
        },
        {
            "id": "2",
            "type": "anythong",
            "data": {
                "args": [None, 3],
                "function": "operator.mul",
            },
            "position": {"x": 612, "y": 259.75},
            "positionAbsolute": {"x": 612, "y": 259.75},
            "width": 210,
            "height": 50,
            "dragging": False,
            "selected": False,
        },
    ],
    "edges": [
        {
            "id": "e1e-e2e",
            "source": "1",
            "sourceHandle": "e-out",
            "target": "2",
            "targetHandle": "e-in",
        },
        {
            "id": "e1-2",
            "source": "1",
            "sourceHandle": "__ignore__",
            "target": "2",
            "targetHandle": "0",
        },
    ],
    "variables": {},
}

sample_branch_flow = {
    "start_id": "1",
    "nodes": [
        {
            "id": "1",
            "type": "Branch",
            "data": {
                "kwargs": {"true": "3", "false": "4"},
                "function": "custom.branch",
            },
            "position": {"x": 1670, "y": 281.25},
            "positionAbsolute": {"x": 1670, "y": 281.25},
            "width": 98,
            "height": 58,
            "selected": False,
            "dragging": False,
        },
    ],
    "edges": [],
    "variables": {},
}

sample_foreach_flow = {
    "start_id": "1",
    "nodes": [
        {
            "id": "1",
            "type": "whateva",
            "data": {
                "kwargs": {"array": "not_used"},
                "function": "custom.for_each",
            },
            "position": {"x": 1670, "y": 281.25},
            "positionAbsolute": {"x": 1670, "y": 281.25},
            "width": 98,
            "height": 58,
            "selected": False,
            "dragging": False,
        },
        {
            "id": "2",
            "type": "whateva",
            "data": {
                "args": [None, 3],
                "function": "operator.mul",
            },
            "position": {"x": 1670, "y": 281.25},
            "positionAbsolute": {"x": 1670, "y": 281.25},
            "width": 98,
            "height": 58,
            "selected": False,
            "dragging": False,
        },
        {
            "id": "3",
            "type": "whateva",
            "data": {
                "kwargs": {"variable_name": "test", "value": "success"},
                "function": "custom.set_variable",
            },
            "position": {"x": 1670, "y": 281.25},
            "positionAbsolute": {"x": 1670, "y": 281.25},
            "width": 98,
            "height": 58,
            "selected": False,
            "dragging": False,
        },
    ],
    "edges": [
        {
            "id": "e1e-e2e",
            "source": "1",
            "sourceHandle": "e-out",
            "target": "2",
            "targetHandle": "e-in",
        },
        {
            "id": "e1-2",
            "source": "1",
            "sourceHandle": "__ignore__",
            "target": "2",
            "targetHandle": "0",
        },
        {
            "id": "e2e-e3e",
            "source": "2",
            "sourceHandle": "e-out",
            "target": "3",
            "targetHandle": "e-in",
        },
    ],
    "variables": {"test": "test"},
}

sample_sequence_flow = {
    "start_id": "1",
    "nodes": [
        {
            "id": "1",
            "type": "whateva",
            "data": {
                "kwargs": {"array": "not_used"},
                "function": "custom.sequence",
            },
            "position": {"x": 1670, "y": 281.25},
            "positionAbsolute": {"x": 1670, "y": 281.25},
            "width": 98,
            "height": 58,
            "selected": False,
            "dragging": False,
        },
        {
            "id": "2",
            "type": "whateva",
            "data": {
                "args": [1, 3],
                "function": "operator.mul",
            },
            "position": {"x": 1670, "y": 281.25},
            "positionAbsolute": {"x": 1670, "y": 281.25},
            "width": 98,
            "height": 58,
            "selected": False,
            "dragging": False,
        },
        {
            "id": "3",
            "type": "whateva",
            "data": {
                "args": [3, 3],
                "function": "operator.mul",
            },
            "position": {"x": 1670, "y": 281.25},
            "positionAbsolute": {"x": 1670, "y": 281.25},
            "width": 98,
            "height": 58,
            "selected": False,
            "dragging": False,
        },
    ],
    "edges": [],
    "variables": {"1": None},
}
